#include "engine/forward.h"
#include "model/model.h"

#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

/* --- 2a: arg validation -------------------------------------------------- */

static void test_arg_validation(void) {
    model_config_t cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.head_dim = 128;
    cfg.rope_scaling_type = "llama3";
    cfg.rope_theta = 500000.0f;
    cfg.rope_scaling_factor = 8.0f;
    cfg.rope_low_freq_factor = 1.0f;
    cfg.rope_high_freq_factor = 4.0f;
    cfg.rope_original_max_position_embeddings = 8192;

    float out[64];

    assert(fwd_rope_llama3_freqs(NULL, out, 64) == -1);
    assert(fwd_rope_llama3_freqs(&cfg, NULL, 64) == -1);
    assert(fwd_rope_llama3_freqs(&cfg, out, 32) == -1);

    model_config_t cfg2 = cfg;
    cfg2.rope_scaling_type = "linear";
    assert(fwd_rope_llama3_freqs(&cfg2, out, 64) == -1);

    model_config_t cfg3 = cfg;
    cfg3.rope_scaling_type = NULL;
    assert(fwd_rope_llama3_freqs(&cfg3, out, 64) == -1);
}

/* --- 2b: high-frequency band passthrough --------------------------------- */

static void test_high_freq_passthrough(void) {
    model_config_t cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.head_dim = 128;
    cfg.rope_scaling_type = "llama3";
    cfg.rope_theta = 500000.0f;
    cfg.rope_scaling_factor = 8.0f;
    cfg.rope_low_freq_factor = 1.0f;
    cfg.rope_high_freq_factor = 4.0f;
    cfg.rope_original_max_position_embeddings = 8192;

    float out[64];
    assert(fwd_rope_llama3_freqs(&cfg, out, 64) == 0);

    for (int i = 0; i < 29; i++) {
        double expected = 1.0 / pow(500000.0, 2.0 * i / 128.0);
        float diff = fabsf(out[i] - (float)expected);
        float rel = diff / (fabsf((float)expected) + 1e-30f);
        assert(rel < 1e-5f);
    }
}

/* --- 2c: low-frequency band ---------------------------------------------- */

static void test_low_freq_scaled(void) {
    model_config_t cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.head_dim = 128;
    cfg.rope_scaling_type = "llama3";
    cfg.rope_theta = 500000.0f;
    cfg.rope_scaling_factor = 8.0f;
    cfg.rope_low_freq_factor = 1.0f;
    cfg.rope_high_freq_factor = 4.0f;
    cfg.rope_original_max_position_embeddings = 8192;

    float out[64];
    assert(fwd_rope_llama3_freqs(&cfg, out, 64) == 0);

    for (int i = 35; i < 64; i++) {
        double base_freq = 1.0 / pow(500000.0, 2.0 * i / 128.0);
        double expected = base_freq / 8.0;
        float diff = fabsf(out[i] - (float)expected);
        float rel = diff / (fabsf((float)expected) + 1e-30f);
        assert(rel < 1e-5f);
    }
}

/* --- 2d: medium band smooth interpolation -------------------------------- */

static void test_medium_band(void) {
    model_config_t cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.head_dim = 128;
    cfg.rope_scaling_type = "llama3";
    cfg.rope_theta = 500000.0f;
    cfg.rope_scaling_factor = 8.0f;
    cfg.rope_low_freq_factor = 1.0f;
    cfg.rope_high_freq_factor = 4.0f;
    cfg.rope_original_max_position_embeddings = 8192;

    float out[64];
    assert(fwd_rope_llama3_freqs(&cfg, out, 64) == 0);

    /* dim 29: hand-computed smooth = 0.803621, expected = 2.16657076e-03 */
    float diff = fabsf(out[29] - 2.16657076e-03f);
    float rel = diff / 2.16657076e-03f;
    assert(rel < 1e-5f);
}

/* --- 2e: full golden vector ---------------------------------------------- */

/* Generated by: python3 -c "... mlx-lm Llama3RoPE formula ..."
   Parameters: dims=128, base=500000, factor=8.0, low=1.0, high=4.0, old_ctx=8192 */
static const float golden[64] = {
    1.00000000e+00f, 8.14617234e-01f, 6.63601238e-01f, 5.40581005e-01f,
    4.40366603e-01f, 3.58730224e-01f, 2.92227823e-01f, 2.38053820e-01f,
    1.93922745e-01f, 1.57972810e-01f, 1.28687373e-01f, 1.04830952e-01f,
    8.53971003e-02f, 6.95659496e-02f, 5.66696214e-02f, 4.61640503e-02f,
    3.76060309e-02f, 3.06345209e-02f, 2.49554087e-02f, 2.03291060e-02f,
    1.65604401e-02f, 1.34904199e-02f, 1.09895285e-02f, 8.95225934e-03f,
    7.29266474e-03f, 5.94073038e-03f, 4.83942135e-03f, 3.94227603e-03f,
    3.21144599e-03f, 2.16657076e-03f, 1.37189357e-03f, 8.56751413e-04f,
    5.24846161e-04f, 3.12693750e-04f, 1.78507813e-04f, 9.55621235e-05f,
    7.78465527e-05f, 6.34151435e-05f, 5.16590687e-05f, 4.20823677e-05f,
    3.42810220e-05f, 2.79259113e-05f, 2.27489286e-05f, 1.85316693e-05f,
    1.50962172e-05f, 1.22976387e-05f, 1.00178684e-05f, 8.16072825e-06f,
    6.64786987e-06f, 5.41546937e-06f, 4.41153467e-06f, 3.59371217e-06f,
    2.92749987e-06f, 2.38479185e-06f, 1.94269254e-06f, 1.58255082e-06f,
    1.28917317e-06f, 1.05018268e-06f, 8.55496913e-07f, 6.96902529e-07f,
    5.67708810e-07f, 4.62465381e-07f, 3.76732269e-07f, 3.06892599e-07f,
};

static void test_golden_vector(void) {
    model_config_t cfg;
    int rc = model_config_load(&cfg, MLXD_FIXTURES_DIR "/model_config_llama3");
    assert(rc == 0);

    int n = cfg.head_dim / 2;
    assert(n == 64);

    float out[64];
    assert(fwd_rope_llama3_freqs(&cfg, out, n) == 0);

    for (int i = 0; i < n; i++) {
        float diff = fabsf(out[i] - golden[i]);
        float rel = diff / (fabsf(golden[i]) + 1e-30f);
        if (rel >= 1e-5f) {
            fprintf(stderr, "golden mismatch at dim %d: got %.8e, want %.8e (rel %.2e)\n",
                    i, out[i], golden[i], (double)rel);
        }
        assert(rel < 1e-5f);
    }

    model_config_free(&cfg);
}

int main(void) {
    test_arg_validation();
    printf("  test_arg_validation: passed\n");

    test_high_freq_passthrough();
    printf("  test_high_freq_passthrough: passed\n");

    test_low_freq_scaled();
    printf("  test_low_freq_scaled: passed\n");

    test_medium_band();
    printf("  test_medium_band: passed\n");

    test_golden_vector();
    printf("  test_golden_vector: passed\n");

    printf("test_rope_llama3: all passed\n");
    return 0;
}
